services:
  postgres:
    image: postgres:15
    container_name: postgres_parasitados
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESS_DATABASE}
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-data:
  pgdata:
